// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIts8fiG971n25qCajM-1XwDr-YPdzALs',
    appId: '1:469081308362:web:2e31835bb7b37841db0833',
    messagingSenderId: '469081308362',
    projectId: 'flutterapp-d9674',
    authDomain: 'flutterapp-d9674.firebaseapp.com',
    storageBucket: 'flutterapp-d9674.appspot.com',
    measurementId: 'G-JG6CP5CP3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPB4QaNJwyWxG4sUYfByx67k7vArZq0bc',
    appId: '1:469081308362:android:296b48b9b366d807db0833',
    messagingSenderId: '469081308362',
    projectId: 'flutterapp-d9674',
    storageBucket: 'flutterapp-d9674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7NaQ936qVeERt3oA2hMGutXwOfUR1gP0',
    appId: '1:469081308362:ios:fa91229fd35a4058db0833',
    messagingSenderId: '469081308362',
    projectId: 'flutterapp-d9674',
    storageBucket: 'flutterapp-d9674.appspot.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7NaQ936qVeERt3oA2hMGutXwOfUR1gP0',
    appId: '1:469081308362:ios:fa91229fd35a4058db0833',
    messagingSenderId: '469081308362',
    projectId: 'flutterapp-d9674',
    storageBucket: 'flutterapp-d9674.appspot.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIts8fiG971n25qCajM-1XwDr-YPdzALs',
    appId: '1:469081308362:web:d31410db82b1240edb0833',
    messagingSenderId: '469081308362',
    projectId: 'flutterapp-d9674',
    authDomain: 'flutterapp-d9674.firebaseapp.com',
    storageBucket: 'flutterapp-d9674.appspot.com',
    measurementId: 'G-PW429K82XX',
  );
}
